### ISSUE TITLE
Preconnect gstatic

### ISSUE THREAD

**Issue by StefanKlatt** [everpress-co/local-google-fonts#8]
### Describe the bug

The line

`<link href='https://fonts.gstatic.com' crossorigin rel='preconnect' />`

appears in the HTML code even all Google fonts are hosted local.
But this shouldn't happen. 

### Steps to Reproduce

Take a look at the HTML code of the Wordpress page

### Environment information

Firefox 103.2

### WordPress information

Wordpress 6.0.1
Theme Twenty Twelve
No optimizing plugins, I deactivated all other plugins for testing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by evrpress** [comment]
Hi there!

Thanks for reporting! This will be fixed in the upcoming version!

Best Regards
